apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-q2ox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-q2ox
    app.kubernetes.io/part-of: cin4s-839-0019-app
  name: devfile-sample-q2ox
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-q2ox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-q2ox
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0019-tenant/cin4s-839-0019-app/devfile-sample-q2ox@sha256:2ea91c8ae87f5dcd7160af0076efb5d78877fdb0996f88061e47544e289206a2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
