apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-q2ox
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0019-tenant/cin4s-839-0019-app/devfile-sample-q2ox@sha256:2ea91c8ae87f5dcd7160af0076efb5d78877fdb0996f88061e47544e289206a2
        name: my-nodejs
        resources: {}
status: {}
